### PR TITLE
Ensured that a user never gets the same Image twice

### LINKED ISSUE #31: Task 3: Error functions and ckeck batch; Deadline: Mi 31.05.23 23:59
## Problem Context
We need error functions and need to check the batch of images a user gets

## Main tasks
- You need to implement error functions in all cases where an error can occur (expecially after user input, before something is shown to the user and when something gets written to a file). These functions should be like in React; you can use try/except/else/finally blocks
- A user should not have to evaluate specific predictions of the same model twice. So make sure that this does not happen

## Optional: Add further information

Requirement: Task 2

### PR DESCRIPTION
**Pull request by tstst334**
Resolves #31 

## Changes

Added an ensured that a user never gets the same Image twice and implemented a small error function which resolves the most important errors. 

## Additional information and notes

The errors will probably change a lot when we have a new interface so i will revisit this part of the task in another PR once the interface is done.

### CODE REVIEW

**Comment by LillianKuhnn** [comment]
Your implementations look really good. I think it would be great if you could update the Interface.ipynb the same way.
And just a quick question, why did you change to NINCO images again?

**Comment by tstst334** [comment]
I only change the root directory to test both directories. Since the interface imports the Dataset, it is not necessary to reimplement the error function. I will take a look at the model again

**Comment by LillianKuhnn** [comment]
Thank you.
To keep the Interface.ipynb file on track could you maybe update some function calls by adding parameters to the calls of createRandomBatch, feedModel and loadDataFromModel. I think altogether 4 calls

**Review by LillianKuhnn — APPROVED** [review]
Everything looks great. Thank you!

**Pull request merged**
